#cloud-config
cloud_final_modules:
  - [users-groups, always]
users:
  - name: ansib;e
    groups: [wheel]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh-authorized-keys:
      - ${ansible_key}
